### PR TITLE
Initial content and theme

### PR DESCRIPTION
**Pull request by meagles**
Alright I gave it another pass - was different enough I just went with a new branch. Now using the `hugo-flex` theme which is simple and gets what we need, and we have some basic initial content better mapped out as well. I signed up for a GetForm account for the join form.

### CODE REVIEW

**Comment by renodubois** [comment]
Getting an error with this newest set of changes - the partial `meta.html` is missing, maybe not checked into the repo?

**Comment by meagles** [comment]
> 
> 
> Getting an error with this newest set of changes - the partial `meta.html` is missing, maybe not checked into the repo?

You may need to do another 
```
git submodule init
git submodule update
```
in order to get the `hugo-flex` theme? Give that a shot and see if it works: I think the previous theme had no `meta.html` but the new one does.

**Comment by renodubois** [comment]
Got it - that worked. I'm somewhat interested in removing the submodule dependency entirely, and instead just check all of the theme files directly into the repo. This would simplify setup somewhat, and would also allow us to easily make changes to the main theme repository without having to step through hoops like forking it on GitHub, etc. Interested in your thoughts on that!

**Comment by renodubois** [comment]
The theme and site look great though! Easy to read, the colors are nice, and the information is presented pretty well too.

**Comment by meagles** [comment]
I'm down to check themes into the repo - I don't think we need updates from the source theme, and I'm happy with it for now. What's the best way to check all of that in - just copy them across from the the themes folder? Then I think this is good to merge in.

**Comment by renodubois** [comment]
I'll give it a go real quick - I think it's just as simple as deleting the `.gitmodules` folder and checking it in, but could be some other steps involved there (I'm not too familiar with git submodules)

**Pull request merged**
